export default [{
  label: '基本信息',
  items: [{
    label: '企业名称',
    name: 'name',
    required: true,
    type: 'text',
    placeholder: '请输入完整的企业名称，最长不超过40个字',
    maxlength: 40
  }, {
    label: '城市',
    name: 'cityId',
    type: 'city',
    enableAllCity: false,
    required: true
  }, {
    label: '联系电话',
    name: 'phone',
    required: true,
    type: 'text',
    placeholder: '请输入联系电话'
  }, {
    label: '紧急联系人',
    name: 'emergencyContactName',
    type: 'text',
    placeholder: '请输入紧急联系人姓名'
  }, {
    label: '紧急联系人电话',
    name: 'emergencyContactPhone',
    type: 'text',
    placeholder: '请输入紧急联系人电话'
  }, {
    label: '身份证正面照片',
    name: 'legalPersonIdentityFrontImg',
    type: 'img',
    limit: 1,
    tip: '最多只能上传1张'
  }, {
    label: '营业执照',
    name: 'businessLicenceImg',
    type: 'img',
    required: true,
    limit: 1,
    tip: '最多只能上传1张'
  }, {
    label: '合同照片',
    name: 'contracts',
    type: 'img',
    limit: 10,
    tip: '最多只能上传10张'
  }, {
    label: '员工应交保证金金额',
    name: 'timeShareRentDeposit',
    required: true,
    type: 'number',
    max: 999,
    append: '元',
    controles: false
  }]
}, {
  label: '财务信息',
  items: [{
    label: '银行类别',
    type: 'text',
    name: 'bankCategory',
    placeholder: '请输入银行类别',
    required: true
  }, {
    label: '开户行',
    type: 'text',
    name: 'bankDeposit',
    placeholder: '请输入开户时的支行名称',
    required: true
  }, {
    label: '开户人',
    type: 'text',
    name: 'bankAccountHolder',
    placeholder: '请输入开户人姓名',
    required: true
  }, {
    label: '银行账号',
    type: 'text',
    name: 'bankAccountNo',
    placeholder: '请输入银行账号',
    required: true
  }, {
    label: '统一社会信用代码',
    type: 'text',
    name: 'uniformSocialCreditCode',
    placeholder: '开发票所需的统一社会信用代码',
    required: true
  }]
}, {
  label: '业务信息',
  items: [{
    label: '企业开发人',
    type: 'text',
    name: 'bizMan',
    placeholder: '请输入企业开发人姓名',
    required: true
  }, {
    label: '企业开发人电话',
    type: 'text',
    name: 'bizManPhone',
    placeholder: '请输入企业开发人电话',
    required: true
  }]
}]
