export default [{
  items: [{
    label: '手机号码',
    name: 'mobile',
    type: 'text',
    placeholder: '即该用户登录使用的用户名',
    required: true
  }, {
    label: '姓名',
    name: 'name',
    type: 'text',
    placeholder: '请输入姓名',
    required: true
  }, {
    label: '运维城市',
    name: 'areaId',
    type: 'remoteCity',
    integratedValue: true,
    placeholder: '请选择运维城市',
    isShowAll: false,
    events: {
      change: 'changeCity'
    },
    required: true
    }, {
    label: '角色',
    name: 'roleId',
    type: 'slot',
    value: '',
    required: true
  }, {
    label: '发单片区',
    name: 'userDistricts',
    type: 'slot',
    value: [],
    required: true,
    hidden: true,
    ruleMsg: '请选择片区'
  }, {
    label: '接单片区',
    name: 'userAcceptDistricts',
    type: 'slot',
    value: [],
    required: true,
    hidden: true,
    ruleMsg: '请选择片区'
  }, {
    label: '发单网点',
    name: 'userStations',
    type: 'slot',
    value: [],
    required: true,
    hidden: true,
    ruleMsg: '请选择网点'
  }, {
    label: '接单网点',
    name: 'userAcceptStations',
    type: 'slot',
    value: [],
    required: true,
    hidden: true,
    ruleMsg: '请选择网点'
  }, {
    label: '状态',
    name: 'enabled',
    type: 'radio',
    options: [{
      label: '启用',
      value: true,
      default: true
    }, {
      label: '禁用',
      value: false
    }],
    required: true
  }]
}]
