export default {
  // ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓工单↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
  // 获取工单列表
  GET_WORKORDER: '/service-ratchet/ratchet/admin/task/listAll',
  // 验收工单
  VERIFY_WORKORDER: '/service-ratchet/ratchet/admin/task/verifyTask',
  // 放入抢单池
  PUT_WORKORDER_INTO_POOL: '/service-ratchet/ratchet/admin/task/throwToPool',
  // 指派/改派
  ASSIGN_EXECUTOR: '/service-ratchet/ratchet/admin/task/assignExecutor',
  // 取消工单
  CANCEL_WORKORDER: '/service-ratchet/ratchet/admin/task/closeTask',
  // 获取工单详情
  GET_WORKORDER_DETAIL: '/service-ratchet/ratchet/admin/task/info',
  // 创建工单
  CREATE_WORKORDER: '/service-ratchet/ratchet/task/create',
  // 获取维修类型
  GET_REPAIR_TYPE: '/service-ratchet/ratchet/task/repairTypeList',
  // 获取物料类型
  GET_MATERIAL_TYPE: '/service-ratchet/ratchet/task/materielTypeList',
  // 获取可指派的运维人员列表
  GET_AVAILABLE_OPUSER: '/service-ratchet/ratchet/admin/task/findExecutors',
  // 获取验收通过时的默认网点
  GET_WORKORDER_STATION: '/service-ratchet/ratchet/admin/task/getStation',
  // 导出工单
  EXPORT_WORKORDER_EXCEL: '/optimus/ratchet/task/export',
  // 查看下一条待验收工单
  GET_NEXT_WORKORDER: '/service-ratchet/ratchet/admin/task/nextTask',
  // ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

  // ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓运维用户↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
  // 获取运维人员列表
  GET_OPUSER: '/service-ratchet/ratchet/users',
  // 根据城市查询片区
  GET_DISTRICT_BY_CITY: '/service-car-station/station/district/list',
  // 添加运维用户
  ADD_OPUSER: '/service-ratchet/ratchet/users/add',
  UPDATE_OPUSER: '/service-ratchet/ratchet/users/update',
  // 获取运维用户详情
  GET_OPUSER_DETAIL: '/service-ratchet/ratchet/users/info',
  // 启用/禁用用户
  SWITCH_OPUSER_STATUS: '/service-ratchet/ratchet/users/updateStatus',
  // 重置密码
  RESET_OPUSER_PASSWORD: '/service-ratchet/ratchet/users/resetPwd',
  // ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
  // 挪车记录
  GET_CARMOVE: '/service-ratchet/ratchet/moveCarRecords',
  // 挪车完成
  POST_MOVECOMPLETE: '/service-ratchet/ratchet/moveCarRecords/moveComplete',
  // 强制挪车
  POST_MOVECOMPLETEFORCE: '/service-ratchet/ratchet/moveCarRecords/moveCompleteForce'
}
