export default {
  GET_WORKORDER: '/service-ratchet/ratchet/admin/task/listAll',
  // 验收工单
  VERIFY_WORKORDER: '/service-ratchet/ratchet/admin/task/verifyTask',
  // 放入抢单池
  PUT_WORKORDER_INTO_POOL: '/service-ratchet/ratchet/admin/task/throwToPool',
  // 指派/改派
  ASSIGN_EXECUTOR: '/service-ratchet/ratchet/admin/task/assignExecutor',
  // 取消工单
  CANCEL_WORKORDER: '/service-ratchet/ratchet/admin/task/closeTask',
  // 获取工单详情
  GET_WORKORDER_DETAIL: '/service-ratchet/ratchet/admin/task/info',
  // 创建工单
  CREATE_WORKORDER: '/service-ratchet/ratchet/task/create',
  // 获取维修类型
  GET_REPAIR_TYPE: '/service-ratchet/ratchet/task/repairTypeList',
  // 获取物料类型
  GET_MATERIAL_TYPE: '/service-ratchet/ratchet/task/materielTypeList',
  // 获取可指派的运维人员列表
  GET_AVAILABLE_OPUSER: '/service-ratchet/ratchet/admin/task/findExecutors',
  // 获取验收通过时的默认网点
  GET_WORKORDER_STATION: '/service-ratchet/ratchet/admin/task/getStation',
  // 导出工单
  EXPORT_WORKORDER_EXCEL: '/optimus/ratchet/task/export',
  // 查看下一条待验收工单
  GET_NEXT_WORKORDER: '/service-ratchet/ratchet/admin/task/nextTask',
  // 查看巡检详情
  GET_INSPECTION_INFOR: '/service-ratchet/ratchet/admin/inspection/info/',
  // 误报或暂不处理
  DISTORT_UNDONE: '/service-ratchet/ratchet/admin/inspection/dealItem',
  // 验收工单获取距离
  GET_DISTANCE: '/service-ratchet/ratchet/admin/task/calcDistance'
}
