export default {
  // 获取车型
  CAR_LIST: '/service-car/cars/models/all',
  // 获取全部订单列表
  ALL_ORDER_LIST: '/service-order-short/shortRent/order/all/page',
  // 绑卡
  BIND_CARD: '/service-order-short/shortRent/order/bindCard',
  // 已还车待结算列表
  WAIT_SETTLEMENT: '/service-order-short/shortRent/order/unsettled/page',
  // 待绑车订单
  WAIT_BINDING_CAR: '/service-order-short/shortRent/order/unbindCar/page',
  // 逾期取车订单
  OVERDUE_GET: '/service-order-short/shortRent/order/overdueTake/page',
  // 逾期还车订单
  OVERDUE_RETURN: '/service-order-short/shortRent/order/overdueReturn/page',
  // 财务待处理订单
  FINANCE_PENDING: '/service-order-short/shortRent/order/financePage/page',
  // 订单支付记录
  PAYMENT_RECORD: '/service-order-short/shortRent/order/pay/page',
  // 订单支付记录导出
  PAYMENT_RECORD_EXPORT: 'optimus/shortRent/order/pay/export',
  // 订单日志
  ORDER_LOG: '/service-order-short/shortRent/order/log/page',
  // 所有物料
  MATERIAL_LIST: '/service-order-short/shortRent/materiel/list',
  // 领取物料
  GET_MATERIAL: '/service-order-short/shortRent/order/materiel/receive',
  // 归还物料
  RETURN_MATERIAL: '/service-order-short/shortRent/order/materiel/return',
  // 领取的全部，已还，未还物料
  ALL_GET_RETURN_MATERIAL: '/service-order-short/shortRent/order/materiel/list',
  // 排车列表
  ORDER_CAR_LIST: '/service-order-short/shortRent/station/car/page',
  // 排车
  ORDERCAR: '/service-order-short/shortRent/order/bindCar',
  // 订单结算
  ORDER_SETTLE: '/service-order-short/shortRent/order/settle',
  // 订单详情
  ORDER_INFORMATION: '/service-order-short/shortRent/order/detail',
  // 取消订单
  CANCEL_ORDER: '/service-order-short/shortRent/order/orderCancel',
  // 退款检查
  REFUND_CHECK: '/service-order-short/shortRent/order/refund/check',
  // 退款
  REFOUND: '/service-order-short/shortRent/order/refund',
  // 修改预约时间
  RESET_TIME: '/service-order-short/shortRent/order/modifyExpectTakeTime',
  // 还车
  RETURN_CAR: '/service-order-short/shortRent/order/returnCar',
  // 导出
  EXPORT: '/optimus/shortRent/allOrder/info/export',
  // 待绑车导出
  EXPORT_WAIT_BIND: '/optimus/shortRent/unbindCarOrder/info/export',
  // 还车检查
  RETURN_CAR_CHECK: '/service-order-short/shortRent/order/backReturnCar/check',
  // 设置闲时
  SET_FREE: '/service-order-short/shortRent/order/car/rentable',
  // 发送租车指令
  SEND_RENT_CAR: '/service-order-short/shortRent/order/car/rent',
  // 修改业务员
  UPDATE_SALE_MAN: '/service-order-short/shortRent/order/salesman/add',
  // 订单取消原因
  getAllCancelReason:
    '/service-order-short/shortRent/order/backend/cancelReason',
  // 排车检车
  bindCar: '/service-order-short/shortRent/order/bindCar',
  // 网点列表
  getAllNetworkStation: '/service-car-station/station/searchList',
  // optimus_3.0.3（新增）_排车第一步
  rentCarStepOne: '/service-order-short/shortRent/order/bindCar/stepOne',
  // optimus_3.0.3（修改）_排车列表
  getAllCarsFromStationid: '/service-order-short/shortRent/station/car/page',
  // optimus_3.0.3（新增）_排车第二步
  rentCarStepSecond: '/service-order-short/shortRent/order/bindCar/stepTwo',
  // optimus_3.0.3（新增）还车2强制还车接口
  returnCarCheck: '/service-order-short/shortRent/order/backReturnCar',
  // 还车未结算订单导出
  waitSettlement: '/optimus/shortRent/order/unsettled/export'
}
